## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['NAME'], axis=1)
application_df

,EIN,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

EIN                       34299
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type = application_df['APPLICATION_TYPE'].value_counts()
app_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 1000
application_types_to_replace = list(app_type[app_type < cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_type = application_df['CLASSIFICATION'].value_counts()
class_type

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_type = class_type[class_type > 1]
classification_type

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff = 2000
class_type = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = list(class_type[class_type < class_cutoff].index)


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
Other     6062
C1200     4837
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_application_df = pd.get_dummies(application_df)
dummies_application_df.head()

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,10531628,1,108590,1,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,10547893,1,5000,0,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,10553066,1,6692,1,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,10556103,1,142590,1,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
X = dummies_application_df.drop("IS_SUCCESSFUL", axis=1).values
y = dummies_application_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 50
hidden_nodes_layer3 = 50

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))


# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                2000

 dense_1 (Dense)             (None, 50)                2550

 dense_2 (Dense)             (None, 50)                2550

 dense_3 (Dense)             (None, 1)                 51

=================================================================
Total params: 7151 (27.93 KB)
Trainable params: 7151 (27.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.5796 - accuracy: 0.7161
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7269
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7290
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5545 - accuracy: 0.7296
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7297
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5519 - accuracy: 0.7321
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5496 - accuracy: 0.7328
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7335
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7334
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7358
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7352
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7367
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7366
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5427 - accuracy: 0.7381
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7384
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7378
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5400 - accuracy: 0.7389
Epoch 18/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5397 - accuracy: 0.7393
Epoch 19/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5386 - accuracy: 0.7398
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7404
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7399
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7418
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7406
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7404
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7421
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7415
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7424
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7441
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.7441
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5322 - accuracy: 0.7436
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5318 - accuracy: 0.7438
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7432
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7452
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7453
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7457
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7444
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5290 - accuracy: 0.7449
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7460
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7461
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7451
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7474
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5265 - accuracy: 0.7457
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7466
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7448
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7464
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7456
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7465
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5246 - accuracy: 0.7470
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5241 - accuracy: 0.7480
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5243 - accuracy: 0.7475
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5234 - accuracy: 0.7472
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5232 - accuracy: 0.7475
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5226 - accuracy: 0.7481
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5223 - accuracy: 0.7474
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5231 - accuracy: 0.7481
Epoch 56/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5216 - accuracy: 0.7465
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5233 - accuracy: 0.7466
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5212 - accuracy: 0.7493
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5207 - accuracy: 0.7486
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5222 - accuracy: 0.7467
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5213 - accuracy: 0.7487
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5210 - accuracy: 0.7480
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5208 - accuracy: 0.7474
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5195 - accuracy: 0.7494
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5193 - accuracy: 0.7493
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5202 - accuracy: 0.7487
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5186 - accuracy: 0.7486
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5195 - accuracy: 0.7488
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5189 - accuracy: 0.7488
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5183 - accuracy: 0.7492
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5182 - accuracy: 0.7488
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5175 - accuracy: 0.7491
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5172 - accuracy: 0.7501
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5177 - accuracy: 0.7505
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5173 - accuracy: 0.7503
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5164 - accuracy: 0.7498
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5164 - accuracy: 0.7488
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5167 - accuracy: 0.7498
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5161 - accuracy: 0.7514
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5152 - accuracy: 0.7526
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5148 - accuracy: 0.7529
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5165 - accuracy: 0.7501
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5155 - accuracy: 0.7507
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5144 - accuracy: 0.7513
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5150 - accuracy: 0.7510
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5144 - accuracy: 0.7509
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5144 - accuracy: 0.7495
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5145 - accuracy: 0.7512
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5155 - accuracy: 0.7513
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5135 - accuracy: 0.7502
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5129 - accuracy: 0.7514
Epoch 92/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5137 - accuracy: 0.7512
Epoch 93/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5133 - accuracy: 0.7526
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5130 - accuracy: 0.7524
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5129 - accuracy: 0.7517
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5125 - accuracy: 0.7521
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5123 - accuracy: 0.7522
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5124 - accuracy: 0.7526
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5109 - accuracy: 0.7524
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5121 - accuracy: 0.7507

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5690 - accuracy: 0.7299 - 800ms/epoch - 3ms/step
Loss: 0.568996012210846, Accuracy: 0.729912519454956

In [17]:
# Export our model to HDF5 file
nn.save('h5Files/AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(